CREATE TABLE SPRING_USER_TBL(
	EMAIL	VARCHAR(50) PRIMARY KEY,
	PASSWORD VARCHAR(50) NOT NULL,
	NAME VARCHAR(50) NOT NULL
);

SELECT *
FROM spring_user_tbl;


SELECT *
FROM SPRING_USER_TBL
WHERE email = 'inspire@gmail.com';

/*
ID: SEQUENCE 이용
CATEGORY: CHECK
EMAIL: FOREIHGN KEY
*/

CREATE SEQUENCE SPRING_BLOG_SEQ
START WITH 1
INCREMENT BY 1;

CREATE TABLE SPRING_BLOG_TBL(
	ID INT PRIMARY KEY, -- DEFAULT (NEXT VALUE FOR SPRING_BLOG_SEQ),
	TITLE VARCHAR(50) NOT NULL,
	CONTENT VARCHAR(200) NOT NULL,
	CATEGORY VARCHAR(50) DEFAULT '전체' CHECK (CATEGORY IN ('전체','개발','생활','취미','일상')),
	EMAIL VARCHAR(50) REFERENCES spring_user_tbl(EMAIL)
);

SELECT *
FROM SPRING_BLOG_TBL;



CREATE SEQUENCE COMMENT_SEQ;

CREATE TABLE SPRING_COMMENT_TBL(
	ID INT PRIMARY KEY,
	COMMENT VARCHAR(200) NOT NULL,
	EMAIL VARCHAR(50) REFERENCES spring_user_tbl(EMAIL),
	BLOGID INT REFERENCES SPRING_BLOG_TBL(ID)
);

SELECT *
FROM SPRING_COMMENT_TBL;