-- DAY03 흑흑...이전 값들 다 날라감...
-- DDL: 물리적 저장공간인 테이블 생성과 논리적 저장공간인 VIEW
-- CREATE, ALTER, DROP
-- CONSSTRAINT: PRIMARY KEY, FOREIGN KEY, NOT NULL, UNIQUE, CHECK
-- DEFAULT: DML NULL값이 입력될 때 DEFAULT선언된 값이 자동으로 할당

/* 
CREATE TABLE TABLE_NAME(
		COLUMN_NAME DATATYPE(SIZE) [DEFAULT][CONSTRAINT TYPE],
		[CONSTRAINT TYPE]
);
OBJECT: TABLE, VIEW, INDEX, SEQUENCE, ETC...
*/

DROP DATABASE IF EXISTS TABLEDB; 
CREATE DATABASE TABLEDB;

USE TABLEDB;

DROP TABLE IF EXISTS TB_BLOG;
CREATE TABLE TB_BLOG(
	-- BLOG_ID VARCHAR (50) CONSTRAINT PRIMARY KEY, -- COLUMN CONSTRAINT
	BLOG_ID VARCHAR (50),
	TITLE   VARCHAR(100),
	CONTENT VARCHAR(100),
	EMAIL   VARCHAR(100),
	CREATE_AT DATE,
	PRIMARY KEY(BLOG_ID)-- TABLE CONSTRAINT
);

SELECT * 
FROM TB_BLOG;

-- DML
INSERT INTO TB_BLOG(BLOG_ID, TITLE, CONTENT, EMAIL, CREATE_AT)
VALUES('1','휴','하루마무리', 'JSLIM',SYSDATE());

SELECT * 
FROM TB_BLOG;
-- 한번 더 위의 DML을 실행하면 1이 중복으로 들어가면 안되어서 에러가 뜨는데
-- 이것은 즉 무결성을 유지하고 있다는 뜻

DROP TABLE IF EXISTS TB_BLOG;
CREATE TABLE TB_BLOG(
	-- BLOG_ID VARCHAR (50) CONSTRAINT PRIMARY KEY, -- COLUMN CONSTRAINT
	BLOG_ID VARCHAR (50),
	TITLE   VARCHAR(100),
	CONTENT VARCHAR(100),
	EMAIL   VARCHAR(100),
	CREATE_AT DATE DEFAULT SYSDATE(),
	PRIMARY KEY(BLOG_ID)-- TABLE CONSTRAINT
);

SELECT * 
FROM TB_BLOG;

INSERT INTO TB_BLOG(BLOG_ID, TITLE, CONTENT, EMAIL)
VALUES('1','휴','하루마무리', 'jslim@naver.com');
-- ERROR
INSERT INTO TB_BLOG(BLOG_ID, TITLE, CONTENT, EMAIL)
VALUES(NULL,'휴','하루마무리', 'jslim@naver.com');

DROP TABLE IF EXISTS TB_BLOG;
CREATE TABLE TB_BLOG(
	-- BLOG_ID VARCHAR (50) CONSTRAINT PRIMARY KEY, -- COLUMN CONSTRAINT
	BLOG_ID VARCHAR (50),
	TITLE   VARCHAR(100),
	CONTENT VARCHAR(100),
	EMAIL   VARCHAR(100),
	CATEGORY VARCHAR(10) CHECK(CATEGORY IN ('전체','취미','여행','일상','개발')),
	CREATE_AT DATE DEFAULT SYSDATE(),
	PRIMARY KEY(BLOG_ID)-- TABLE CONSTRAINT
);

INSERT INTO TB_BLOG(BLOG_ID, CATEGORY)
VALUES('1','개발');
